import { useState } from 'react';
import { Coffee, Lock, ShieldCheck, ArrowLeft } from 'lucide-react';
import { api } from '../api';

export function FirstSetup({ onCreated }) {
  const [name,setName]=useState(''); const [pin,setPin]=useState(''); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);
  const valid=name.trim() && /^\d{4,6}$/.test(pin);
  const submit=async()=>{setBusy(true);setErr('');try{await api('setup_owner',{method:'POST',body:{name:name.trim(),pin}});onCreated();}catch(e){setErr(e.message)}finally{setBusy(false)}};
  return <div className="auth-shell"><section className="auth-hero"><div className="auth-brand"><div className="auth-brand-mark"><Coffee size={22}/></div><div><strong>بن الشريب</strong><span>BIN ALSHREEB OPERATIONS</span></div></div><div className="auth-copy"><span>ROASTERY OPERATIONS</span><h1>كل يوم ناجح<br/>يبدأ من شيفت مضبوط.</h1><p>نظام تشغيل ومبيعات بن الشريب — الفروع، الشيفتات، المخزون والتقارير في مكان واحد.</p></div><div className="auth-foot">تشغيل آمن · إدارة متعددة الفروع</div></section><section className="auth-panel"><div className="auth-card"><div className="auth-card-icon"><ShieldCheck size={20}/></div><span className="auth-kicker">إعداد النظام لأول مرة</span><h2>إنشاء حساب الـ Owner</h2><p className="auth-desc">الحساب ده هو صاحب الصلاحيات الكاملة للنظام.</p><input className="auth-input" placeholder="اسم صاحب النظام" value={name} onChange={e=>setName(e.target.value)}/><input className="auth-input pin" placeholder="PIN من 4 لـ 6 أرقام" inputMode="numeric" type="password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/>{err&&<p className="auth-error"><Lock size={14}/>{err}</p>}<button className="auth-submit" disabled={!valid||busy} onClick={submit}>{busy?'جاري الإنشاء…':'إنشاء الحساب والدخول'}<ArrowLeft size={17}/></button><small>لن يتم إنشاء Owner آخر بعد إتمام الإعداد.</small></div></section></div>;
}

export function LoginScreen({ onLogin }) {
  const [pin,setPin]=useState(''); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async()=>{if(!pin)return;setBusy(true);setErr('');try{const r=await api('login',{method:'POST',body:{pin}});onLogin(r.user);}catch(e){setErr(e.message)}finally{setBusy(false)}};
  return <div className="auth-shell"><section className="auth-hero"><div className="auth-brand"><div className="auth-brand-mark"><Coffee size={22}/></div><div><strong>بن الشريب</strong><span>BIN ALSHREEB OPERATIONS</span></div></div><div className="auth-copy"><span>ROASTERY OPERATIONS</span><h1>كل يوم ناجح<br/>يبدأ من شيفت مضبوط.</h1><p>نظام تشغيل ومبيعات بن الشريب — الفروع، الشيفتات، المخزون والتقارير في مكان واحد.</p></div><div className="auth-foot">تشغيل آمن · إدارة متعددة الفروع</div></section><section className="auth-panel"><div className="auth-card"><div className="auth-card-icon"><ShieldCheck size={20}/></div><span className="auth-kicker">تسجيل الدخول</span><h2>أهلاً بيك في بن الشريب</h2><p className="auth-desc">اكتب الـ PIN الخاص بحسابك للدخول.</p><input className="auth-input pin" autoFocus placeholder="الرقم السري" inputMode="numeric" type="password" value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,''));setErr('')}} onKeyDown={e=>e.key==='Enter'&&submit()}/>{err&&<p className="auth-error"><Lock size={14}/>{err}</p>}<button className="auth-submit" disabled={!pin||busy} onClick={submit}>{busy?'جاري التحقق…':'دخول'}<ArrowLeft size={17}/></button><small><ShieldCheck size={12}/> جلسة دخول آمنة ومحمية</small></div></section></div>;
}
