import { useState } from "react";
import { Plus, Trash2, Pencil, Store, X } from "lucide-react";
import { uid, fmt, TYPE_LABEL } from "../lib";
import { EmptyState } from "../components/Nav";

export function SettingsTab({ products, addOrEditProduct, deleteProduct, branches, setBranches, users, addOrEditUser, deleteUser, currentUser }) {
  const [section,setSection]=useState("products"); const [editing,setEditing]=useState(null); const [showBranches,setShowBranches]=useState(false); const [editingUser,setEditingUser]=useState(null);
  return <div>
    <div className="tabs-2" style={{marginBottom:16}}><button className={section==='products'?"tab-active":"tab-inactive"} onClick={()=>setSection('products')}>المنتجات</button><button className={section==='users'?"tab-active":"tab-inactive"} onClick={()=>setSection('users')}>المستخدمين</button><button className="tab-inactive" onClick={()=>setShowBranches(true)}><Store size={14}/> الفروع</button></div>
    {section==='products'&&<div><button className="btn-secondary" style={{background:"var(--accent)",color:"var(--bg)",marginBottom:12}} onClick={()=>setEditing({id:uid(),name:"",type:"bulk",package_weight:"",sell_price:"",cost_price:"",track_stock:true,reorder_point:0})}><Plus size={16}/> منتج جديد</button>{products.map(p=><div key={p.id} className="branch-row"><div style={{display:'flex',gap:12}}><button style={{color:'var(--bad)'}} onClick={()=>deleteProduct(p.id)}><Trash2 size={16}/></button><button style={{color:'var(--muted)'}} onClick={()=>setEditing(p)}><Pencil size={16}/></button></div><div style={{textAlign:'right'}}><p style={{fontWeight:700}}>{p.name}{p.package_weight?` (${p.package_weight}جم)`:''}</p><p className="tiny">{TYPE_LABEL[p.type]} · بيع {fmt(p.sell_price)} ج.م · تكلفة {fmt(p.cost_price)}</p></div></div>)}{!products.length&&<EmptyState text="ضيف أول منتج عشان تبدأ البيع."/>}</div>}
    {section==='users'&&<div><button className="btn-secondary" style={{background:"var(--accent)",color:"var(--bg)",marginBottom:12}} onClick={()=>setEditingUser({id:uid(),name:"",pin:"",role:"cashier",branch_id:"",shift_period:"morning",active:true})}><Plus size={16}/> مستخدم جديد</button><p className="tiny" style={{marginBottom:12}}>Owner واحد فقط. لكل فرع مدير واحد، ولكل فرع كاشير صباحي وكاشير مسائي.</p>{users.map(u=><div key={u.id} className="branch-row"><div style={{display:'flex',gap:12}}>{u.id!==currentUser.id&&<button style={{color:'var(--bad)'}} onClick={()=>deleteUser(u.id)}><Trash2 size={16}/></button>}<button style={{color:'var(--muted)'}} onClick={()=>setEditingUser({...u,pin:''})}><Pencil size={16}/></button></div><div style={{textAlign:'right'}}><p style={{fontWeight:700}}>{u.name}{u.id===currentUser.id?' (الحساب الحالي)':''}</p><p className="tiny">{u.role==='owner'?'Owner — كل الفروع':u.role==='manager'?`مدير — ${branches.find(b=>b.id===u.branch_id)?.name||'—'}`:`كاشير ${u.shift_period==='evening'?'مسائي':'صباحي'} — ${branches.find(b=>b.id===u.branch_id)?.name||'—'}`}</p></div></div>)}</div>}
    {editing&&<ProductEditor product={editing} onClose={()=>setEditing(null)} onSave={p=>{addOrEditProduct(p);setEditing(null)}}/>}
    {showBranches&&<BranchEditor branches={branches} onClose={()=>setShowBranches(false)} onSave={list=>{setBranches(list);setShowBranches(false)}}/>}
    {editingUser&&<UserEditor user={editingUser} branches={branches} users={users} onClose={()=>setEditingUser(null)} onSave={u=>{addOrEditUser(u);setEditingUser(null)}}/>}
  </div>;
}
function UserEditor({user,branches,users,onClose,onSave}){const [u,setU]=useState(user);const [err,setErr]=useState('');const valid=u.name?.trim()&&(!u.pin||/^\d{4,6}$/.test(u.pin))&&(u.role==='owner'||u.branch_id)&&(u.role!=='cashier'||['morning','evening'].includes(u.shift_period));const save=()=>{if(u.role==='owner'&&users.some(x=>x.id!==u.id&&x.role==='owner'&&x.active!==false)){setErr('مسموح Owner واحد فقط');return}if(u.role!=='owner'&&users.some(x=>x.id!==u.id&&x.role===u.role&&x.branch_id===u.branch_id&&x.active!==false&&(u.role!=='cashier'||x.shift_period===u.shift_period))){setErr('الوظيفة دي موجودة بالفعل في نفس الفرع');return}onSave({...u,branch_id:u.role==='owner'?null:u.branch_id,shift_period:u.role==='cashier'?u.shift_period:null})};return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><button className="icon-btn" onClick={onClose}><X size={20}/></button><h3>بيانات المستخدم</h3></div><input className="text-input" placeholder="الاسم" value={u.name||''} onChange={e=>setU({...u,name:e.target.value})}/><input className="text-input" placeholder={u.id?'اتركه فارغًا بدون تغيير الـ PIN':'PIN من 4 لـ 6 أرقام'} inputMode="numeric" type="password" value={u.pin||''} onChange={e=>{setU({...u,pin:e.target.value.replace(/\D/g,'')});setErr('')}}/>{err&&<p className="tiny-bad">{err}</p>}<div className="tabs-2"><button className={u.role==='manager'?'tab-active':'tab-inactive'} onClick={()=>setU({...u,role:'manager',shift_period:null})}>مدير</button><button className={u.role==='cashier'?'tab-active':'tab-inactive'} onClick={()=>setU({...u,role:'cashier',shift_period:u.shift_period||'morning'})}>كاشير</button></div>{u.role!=='owner'&&<select className="select" value={u.branch_id||''} onChange={e=>setU({...u,branch_id:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}{u.role==='cashier'&&<div className="tabs-2"><button className={u.shift_period==='morning'?'tab-active':'tab-inactive'} onClick={()=>setU({...u,shift_period:'morning'})}>صباحي</button><button className={u.shift_period==='evening'?'tab-active':'tab-inactive'} onClick={()=>setU({...u,shift_period:'evening'})}>مسائي</button></div>}<button className="btn btn-primary" disabled={!valid} onClick={save}>حفظ</button></div></div>}
function ProductEditor({product,onClose,onSave}){const [p,setP]=useState(product);const valid=p.name?.trim()&&Number(p.sell_price)>=0&&Number(p.cost_price)>=0;return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><button className="icon-btn" onClick={onClose}><X size={20}/></button><h3>بيانات المنتج</h3></div><input className="text-input" placeholder="اسم المنتج" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/><div className="tabs-2"><button className={p.type==='bulk'?'tab-active':'tab-inactive'} onClick={()=>setP({...p,type:'bulk'})}>بن سايب</button><button className={p.type==='packaged'?'tab-active':'tab-inactive'} onClick={()=>setP({...p,type:'packaged'})}>علبة</button><button className={p.type==='piece'?'tab-active':'tab-inactive'} onClick={()=>setP({...p,type:'piece'})}>قطعة</button></div>{p.type==='packaged'&&<input className="text-input" type="number" placeholder="وزن العلبة بالجرام" value={p.package_weight||''} onChange={e=>setP({...p,package_weight:e.target.value})}/>}<input className="text-input" type="number" placeholder={p.type==='bulk'?'سعر البيع لكل كيلو':'سعر البيع للوحدة'} value={p.sell_price} onChange={e=>setP({...p,sell_price:e.target.value})}/><input className="text-input" type="number" placeholder={p.type==='bulk'?'التكلفة لكل كيلو':'التكلفة للوحدة'} value={p.cost_price} onChange={e=>setP({...p,cost_price:e.target.value})}/><label className="checkbox-row"><input type="checkbox" checked={p.track_stock!==false} onChange={e=>setP({...p,track_stock:e.target.checked})}/> تتبع المخزون</label>{p.track_stock&&<input className="text-input" type="number" placeholder="حد إعادة الطلب" value={p.reorder_point||0} onChange={e=>setP({...p,reorder_point:Number(e.target.value)})}/>}<button className="btn btn-primary" disabled={!valid} onClick={()=>onSave({...p,sell_price:Number(p.sell_price),cost_price:Number(p.cost_price||0),package_weight:p.package_weight?Number(p.package_weight):null})}>حفظ</button></div></div>}
function BranchEditor({branches,onClose,onSave}){const [list,setList]=useState(branches);return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><button className="icon-btn" onClick={onClose}><X size={20}/></button><h3>أسماء الفروع</h3></div>{list.map((b,i)=><input key={b.id} className="text-input" value={b.name} onChange={e=>setList(list.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/>)}<button className="btn btn-primary" onClick={()=>onSave(list)}>حفظ</button></div></div>}
